# Generated by Django 4.0.1 on 2022-02-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink_Rating_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkid', models.CharField(max_length=256, null=True)),
                ('score', models.CharField(max_length=256, null=True)),
                ('timestamp', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'drink_ratings',
            },
        ),
    ]
