# Generated by Django 4.0.1 on 2022-02-08 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256, null=True)),
                ('img', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('price', models.CharField(max_length=256, null=True)),
                ('description', models.CharField(max_length=256, null=True)),
                ('score', models.CharField(max_length=256, null=True)),
                ('alcohol', models.CharField(max_length=256, null=True)),
                ('style_info', models.CharField(max_length=256, null=True)),
                ('aroma_info', models.CharField(max_length=256, null=True)),
                ('flavor_info', models.CharField(max_length=256, null=True)),
                ('finish_info', models.CharField(max_length=256, null=True)),
                ('smoothness_info', models.CharField(max_length=256, null=True)),
                ('enjoy_info', models.CharField(max_length=256, null=True)),
                ('pairing_info', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'drink_db',
            },
        ),
    ]
