# Generated by Django 4.0.1 on 2022-02-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkmodel',
            name='page',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
