# Generated by Django 4.0.2 on 2022-02-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=256, null=True)),
                ('img', models.CharField(max_length=256, null=True)),
                ('title', models.CharField(max_length=256, null=True)),
                ('price', models.CharField(max_length=256, null=True)),
                ('score', models.CharField(max_length=256, null=True)),
            ],
            options={
                'db_table': 'food_db',
            },
        ),
    ]
